# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Memorial Descritivo - Programa
tagline:          byander
url:              http://byander.github.io/memorial_descritivo/
paginate:         1
baseurl:          /
author:
  name:           Anderson 
  url:            https://twitter.com/byander
  email:          byander@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/byander/memorial_descritivo
